AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'Vagrantfile'

Style/Documentation:
  Enabled: False

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
  ExcludedMethods: ['describe', 'context']

Style/EmptyMethod:
  EnforcedStyle: expanded
